In [3]:
from chessdotcom import ChessDotComClient
import re
import datetime
import pytz
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [221]:
### Enter Chess.com username to begin ###
client = ChessDotComClient(user_agent = "My Python Application...")
response = 0
while response == 0:
    username = str(input("Enter Username: "))
    try:
        response = client.get_player_profile(username)
        print('Username entered successfully')
    except chessdotcom.errors.ChessDotComClientError:
        print('Invalid Username')

# reassigning the username variable to the value stored on chess.com
url = response.player.url
pattern = r'[^/]+$'
match = re.findall(pattern, url)
username = match[0]

Enter Username:  hikaru

Username entered successfully

In [7]:
tz_list = []
for tz in pytz.all_timezones:
    print(tz)
    tz_list.append(tz)

Africa/Abidjan
Africa/Accra
Africa/Addis_Ababa
Africa/Algiers
Africa/Asmara
Africa/Asmera
Africa/Bamako
Africa/Bangui
Africa/Banjul
Africa/Bissau
Africa/Blantyre
Africa/Brazzaville
Africa/Bujumbura
Africa/Cairo
Africa/Casablanca
Africa/Ceuta
Africa/Conakry
Africa/Dakar
Africa/Dar_es_Salaam
Africa/Djibouti
Africa/Douala
Africa/El_Aaiun
Africa/Freetown
Africa/Gaborone
Africa/Harare
Africa/Johannesburg
Africa/Juba
Africa/Kampala
Africa/Khartoum
Africa/Kigali
Africa/Kinshasa
Africa/Lagos
Africa/Libreville
Africa/Lome
Africa/Luanda
Africa/Lubumbashi
Africa/Lusaka
Africa/Malabo
Africa/Maputo
Africa/Maseru
Africa/Mbabane
Africa/Mogadishu
Africa/Monrovia
Africa/Nairobi
Africa/Ndjamena
Africa/Niamey
Africa/Nouakchott
Africa/Ouagadougou
Africa/Porto-Novo
Africa/Sao_Tome
Africa/Timbuktu
Africa/Tripoli
Africa/Tunis
Africa/Windhoek
America/Adak
America/Anchorage
America/Anguilla
America/Antigua
America/Araguaina
America/Argentina/Buenos_Aires
America/Argentina/Catamarca
America/Argentina/ComodRivadavia
America/Argentina/Cordoba
America/Argentina/Jujuy
America/Argentina/La_Rioja
America/Argentina/Mendoza
America/Argentina/Rio_Gallegos
America/Argentina/Salta
America/Argentina/San_Juan
America/Argentina/San_Luis
America/Argentina/Tucuman
America/Argentina/Ushuaia
America/Aruba
America/Asuncion
America/Atikokan
America/Atka
America/Bahia
America/Bahia_Banderas
America/Barbados
America/Belem
America/Belize
America/Blanc-Sablon
America/Boa_Vista
America/Bogota
America/Boise
America/Buenos_Aires
America/Cambridge_Bay
America/Campo_Grande
America/Cancun
America/Caracas
America/Catamarca
America/Cayenne
America/Cayman
America/Chicago
America/Chihuahua
America/Ciudad_Juarez
America/Coral_Harbour
America/Cordoba
America/Costa_Rica
America/Creston
America/Cuiaba
America/Curacao
America/Danmarkshavn
America/Dawson
America/Dawson_Creek
America/Denver
America/Detroit
America/Dominica
America/Edmonton
America/Eirunepe
America/El_Salvador
America/Ensenada
America/Fort_Nelson
America/Fort_Wayne
America/Fortaleza
America/Glace_Bay
America/Godthab
America/Goose_Bay
America/Grand_Turk
America/Grenada
America/Guadeloupe
America/Guatemala
America/Guayaquil
America/Guyana
America/Halifax
America/Havana
America/Hermosillo
America/Indiana/Indianapolis
America/Indiana/Knox
America/Indiana/Marengo
America/Indiana/Petersburg
America/Indiana/Tell_City
America/Indiana/Vevay
America/Indiana/Vincennes
America/Indiana/Winamac
America/Indianapolis
America/Inuvik
America/Iqaluit
America/Jamaica
America/Jujuy
America/Juneau
America/Kentucky/Louisville
America/Kentucky/Monticello
America/Knox_IN
America/Kralendijk
America/La_Paz
America/Lima
America/Los_Angeles
America/Louisville
America/Lower_Princes
America/Maceio
America/Managua
America/Manaus
America/Marigot
America/Martinique
America/Matamoros
America/Mazatlan
America/Mendoza
America/Menominee
America/Merida
America/Metlakatla
America/Mexico_City
America/Miquelon
America/Moncton
America/Monterrey
America/Montevideo
America/Montreal
America/Montserrat
America/Nassau
America/New_York
America/Nipigon
America/Nome
America/Noronha
America/North_Dakota/Beulah
America/North_Dakota/Center
America/North_Dakota/New_Salem
America/Nuuk
America/Ojinaga
America/Panama
America/Pangnirtung
America/Paramaribo
America/Phoenix
America/Port-au-Prince
America/Port_of_Spain
America/Porto_Acre
America/Porto_Velho
America/Puerto_Rico
America/Punta_Arenas
America/Rainy_River
America/Rankin_Inlet
America/Recife
America/Regina
America/Resolute
America/Rio_Branco
America/Rosario
America/Santa_Isabel
America/Santarem
America/Santiago
America/Santo_Domingo
America/Sao_Paulo
America/Scoresbysund
America/Shiprock
America/Sitka
America/St_Barthelemy
America/St_Johns
America/St_Kitts
America/St_Lucia
America/St_Thomas
America/St_Vincent
America/Swift_Current
America/Tegucigalpa
America/Thule
America/Thunder_Bay
America/Tijuana
America/Toronto
America/Tortola
America/Vancouver
America/Virgin
America/Whitehorse
America/Winnipeg
America/Yakutat
America/Yellowknife
Antarctica/Casey
Antarctica/Davis
Antarctica/DumontDUrville
Antarctica/Macquarie
Antarctica/Mawson
Antarctica/McMurdo
Antarctica/Palmer
Antarctica/Rothera
Antarctica/South_Pole
Antarctica/Syowa
Antarctica/Troll
Antarctica/Vostok
Arctic/Longyearbyen
Asia/Aden
Asia/Almaty
Asia/Amman
Asia/Anadyr
Asia/Aqtau
Asia/Aqtobe
Asia/Ashgabat
Asia/Ashkhabad
Asia/Atyrau
Asia/Baghdad
Asia/Bahrain
Asia/Baku
Asia/Bangkok
Asia/Barnaul
Asia/Beirut
Asia/Bishkek
Asia/Brunei
Asia/Calcutta
Asia/Chita
Asia/Choibalsan
Asia/Chongqing
Asia/Chungking
Asia/Colombo
Asia/Dacca
Asia/Damascus
Asia/Dhaka
Asia/Dili
Asia/Dubai
Asia/Dushanbe
Asia/Famagusta
Asia/Gaza
Asia/Harbin
Asia/Hebron
Asia/Ho_Chi_Minh
Asia/Hong_Kong
Asia/Hovd
Asia/Irkutsk
Asia/Istanbul
Asia/Jakarta
Asia/Jayapura
Asia/Jerusalem
Asia/Kabul
Asia/Kamchatka
Asia/Karachi
Asia/Kashgar
Asia/Kathmandu
Asia/Katmandu
Asia/Khandyga
Asia/Kolkata
Asia/Krasnoyarsk
Asia/Kuala_Lumpur
Asia/Kuching
Asia/Kuwait
Asia/Macao
Asia/Macau
Asia/Magadan
Asia/Makassar
Asia/Manila
Asia/Muscat
Asia/Nicosia
Asia/Novokuznetsk
Asia/Novosibirsk
Asia/Omsk
Asia/Oral
Asia/Phnom_Penh
Asia/Pontianak
Asia/Pyongyang
Asia/Qatar
Asia/Qostanay
Asia/Qyzylorda
Asia/Rangoon
Asia/Riyadh
Asia/Saigon
Asia/Sakhalin
Asia/Samarkand
Asia/Seoul
Asia/Shanghai
Asia/Singapore
Asia/Srednekolymsk
Asia/Taipei
Asia/Tashkent
Asia/Tbilisi
Asia/Tehran
Asia/Tel_Aviv
Asia/Thimbu
Asia/Thimphu
Asia/Tokyo
Asia/Tomsk
Asia/Ujung_Pandang
Asia/Ulaanbaatar
Asia/Ulan_Bator
Asia/Urumqi
Asia/Ust-Nera
Asia/Vientiane
Asia/Vladivostok
Asia/Yakutsk
Asia/Yangon
Asia/Yekaterinburg
Asia/Yerevan
Atlantic/Azores
Atlantic/Bermuda
Atlantic/Canary
Atlantic/Cape_Verde
Atlantic/Faeroe
Atlantic/Faroe
Atlantic/Jan_Mayen
Atlantic/Madeira
Atlantic/Reykjavik
Atlantic/South_Georgia
Atlantic/St_Helena
Atlantic/Stanley
Australia/ACT
Australia/Adelaide
Australia/Brisbane
Australia/Broken_Hill
Australia/Canberra
Australia/Currie
Australia/Darwin
Australia/Eucla
Australia/Hobart
Australia/LHI
Australia/Lindeman
Australia/Lord_Howe
Australia/Melbourne
Australia/NSW
Australia/North
Australia/Perth
Australia/Queensland
Australia/South
Australia/Sydney
Australia/Tasmania
Australia/Victoria
Australia/West
Australia/Yancowinna
Brazil/Acre
Brazil/DeNoronha
Brazil/East
Brazil/West
CET
CST6CDT
Canada/Atlantic
Canada/Central
Canada/Eastern
Canada/Mountain
Canada/Newfoundland
Canada/Pacific
Canada/Saskatchewan
Canada/Yukon
Chile/Continental
Chile/EasterIsland
Cuba
EET
EST
EST5EDT
Egypt
Eire
Etc/GMT
Etc/GMT+0
Etc/GMT+1
Etc/GMT+10
Etc/GMT+11
Etc/GMT+12
Etc/GMT+2
Etc/GMT+3
Etc/GMT+4
Etc/GMT+5
Etc/GMT+6
Etc/GMT+7
Etc/GMT+8
Etc/GMT+9
Etc/GMT-0
Etc/GMT-1
Etc/GMT-10
Etc/GMT-11
Etc/GMT-12
Etc/GMT-13
Etc/GMT-14
Etc/GMT-2
Etc/GMT-3
Etc/GMT-4
Etc/GMT-5
Etc/GMT-6
Etc/GMT-7
Etc/GMT-8
Etc/GMT-9
Etc/GMT0
Etc/Greenwich
Etc/UCT
Etc/UTC
Etc/Universal
Etc/Zulu
Europe/Amsterdam
Europe/Andorra
Europe/Astrakhan
Europe/Athens
Europe/Belfast
Europe/Belgrade
Europe/Berlin
Europe/Bratislava
Europe/Brussels
Europe/Bucharest
Europe/Budapest
Europe/Busingen
Europe/Chisinau
Europe/Copenhagen
Europe/Dublin
Europe/Gibraltar
Europe/Guernsey
Europe/Helsinki
Europe/Isle_of_Man
Europe/Istanbul
Europe/Jersey
Europe/Kaliningrad
Europe/Kiev
Europe/Kirov
Europe/Kyiv
Europe/Lisbon
Europe/Ljubljana
Europe/London
Europe/Luxembourg
Europe/Madrid
Europe/Malta
Europe/Mariehamn
Europe/Minsk
Europe/Monaco
Europe/Moscow
Europe/Nicosia
Europe/Oslo
Europe/Paris
Europe/Podgorica
Europe/Prague
Europe/Riga
Europe/Rome
Europe/Samara
Europe/San_Marino
Europe/Sarajevo
Europe/Saratov
Europe/Simferopol
Europe/Skopje
Europe/Sofia
Europe/Stockholm
Europe/Tallinn
Europe/Tirane
Europe/Tiraspol
Europe/Ulyanovsk
Europe/Uzhgorod
Europe/Vaduz
Europe/Vatican
Europe/Vienna
Europe/Vilnius
Europe/Volgograd
Europe/Warsaw
Europe/Zagreb
Europe/Zaporozhye
Europe/Zurich
GB
GB-Eire
GMT
GMT+0
GMT-0
GMT0
Greenwich
HST
Hongkong
Iceland
Indian/Antananarivo
Indian/Chagos
Indian/Christmas
Indian/Cocos
Indian/Comoro
Indian/Kerguelen
Indian/Mahe
Indian/Maldives
Indian/Mauritius
Indian/Mayotte
Indian/Reunion
Iran
Israel
Jamaica
Japan
Kwajalein
Libya
MET
MST
MST7MDT
Mexico/BajaNorte
Mexico/BajaSur
Mexico/General
NZ
NZ-CHAT
Navajo
PRC
PST8PDT
Pacific/Apia
Pacific/Auckland
Pacific/Bougainville
Pacific/Chatham
Pacific/Chuuk
Pacific/Easter
Pacific/Efate
Pacific/Enderbury
Pacific/Fakaofo
Pacific/Fiji
Pacific/Funafuti
Pacific/Galapagos
Pacific/Gambier
Pacific/Guadalcanal
Pacific/Guam
Pacific/Honolulu
Pacific/Johnston
Pacific/Kanton
Pacific/Kiritimati
Pacific/Kosrae
Pacific/Kwajalein
Pacific/Majuro
Pacific/Marquesas
Pacific/Midway
Pacific/Nauru
Pacific/Niue
Pacific/Norfolk
Pacific/Noumea
Pacific/Pago_Pago
Pacific/Palau
Pacific/Pitcairn
Pacific/Pohnpei
Pacific/Ponape
Pacific/Port_Moresby
Pacific/Rarotonga
Pacific/Saipan
Pacific/Samoa
Pacific/Tahiti
Pacific/Tarawa
Pacific/Tongatapu
Pacific/Truk
Pacific/Wake
Pacific/Wallis
Pacific/Yap
Poland
Portugal
ROC
ROK
Singapore
Turkey
UCT
US/Alaska
US/Aleutian
US/Arizona
US/Central
US/East-Indiana
US/Eastern
US/Hawaii
US/Indiana-Starke
US/Michigan
US/Mountain
US/Pacific
US/Samoa
UTC
Universal
W-SU
WET
Zulu

In [223]:
while True:
    timezone = str(input("Enter Timezone: "))
    if timezone in tz_list:
        print('Timezone entered successfully')
        break
    else:
        print('Invalid Timezone')

Enter Timezone:  US/Eastern

Timezone entered successfully

In [225]:
### Get player profile ###

if response.player.name is None:
    name = pd.NA
else: 
    name = response.player.name

if response.player.country is None:
    country = pd.NA
else: 
    response_country = client.get_country_details(response.player.country[-2:])
    country = response_country.country.name

if response.player.joined is None:
    joined = pd.NA
else: 
    joined = datetime.datetime.fromtimestamp(response.player.joined)

if response.player.last_online is None:
    last_online = pd.NA
else: 
    last_online = datetime.datetime.fromtimestamp(response.player.last_online)

profile = {
    "Profile_Info": ["Name", "Country", "Joined", "Last Online"],
    username: [name, country, joined, last_online]}

df = pd.DataFrame(profile)
df.set_index("Profile_Info", inplace=True)
df = df.rename_axis(None)
df

                          Hikaru
Name             Hikaru Nakamura
Country            United States
Joined       2014-01-06 16:20:58
Last Online  2024-11-29 03:40:58

In [227]:
### Get all-time player stats ###

response2 = client.get_player_stats(username)

if response2.stats.chess_rapid is None:
    rapid_rating = pd.NA
    rapid_wld = pd.NA
else: 
    rapid_rating = response2.stats.chess_rapid.last.rating
    rapid_wld = f"{str(response2.stats.chess_rapid.record.win)}-{str(response2.stats.chess_rapid.record.loss)}-{str(response2.stats.chess_rapid.record.draw)}"

if response2.stats.chess_blitz is None:
    blitz_rating = pd.NA
    blitz_wld = pd.NA
else: 
    blitz_rating = response2.stats.chess_blitz.last.rating
    blitz_wld = f"{str(response2.stats.chess_blitz.record.win)}-{str(response2.stats.chess_blitz.record.loss)}-{str(response2.stats.chess_blitz.record.draw)}"
    
if response2.stats.chess_bullet is None:
    bullet_rating = pd.NA
    bullet_wld = pd.NA
else: 
    bullet_rating = response2.stats.chess_bullet.last.rating
    bullet_wld = f"{str(response2.stats.chess_bullet.record.win)}-{str(response2.stats.chess_bullet.record.loss)}-{str(response2.stats.chess_bullet.record.draw)}"

if response2.stats.chess_daily is None:
    daily_rating = pd.NA
    daily_wld = pd.NA
else: 
    daily_rating = response2.stats.chess_daily.last.rating
    daily_wld = f"{str(response2.stats.chess_daily.record.win)}-{str(response2.stats.chess_daily.record.loss)}-{str(response2.stats.chess_daily.record.draw)}"

stats = {
    "Profile_Info": ["Rapid Chess Rating", "Rapid Chess Record",
                     "Blitz Chess Rating", "Blitz Chess Record",
                     "Bullet Chess Rating", "Bullet Chess Record",
                     "Daily Chess Rating", "Daily Chess Record"],
    "Username": [rapid_rating, rapid_wld,
                 blitz_rating, blitz_wld,
                 bullet_rating, bullet_wld,
                 daily_rating, daily_wld
                 ]}

df = pd.DataFrame(stats)
df.rename(columns={"Username": username}, inplace=True)
df.set_index("Profile_Info", inplace=True)
df = df.rename_axis(None)
df

                              Hikaru
Rapid Chess Rating              2769
Rapid Chess Record        182-53-184
Blitz Chess Rating              3231
Blitz Chess Record   29650-4921-3881
Bullet Chess Rating             3319
Bullet Chess Record   14246-1967-899
Daily Chess Rating              2239
Daily Chess Record           73-11-4

In [229]:
## Make a dataframe of all games the player has ever played ##
response3 = client.get_player_game_archives(username)
months_list = []
for i in range(len(response3.archives)):
    months_list.append(response3.archives[i][-7:])

live_games = []
for i in range(len(months_list)):
    year = int(months_list[i][:4])
    month = int(months_list[i][5:])
    response4 = client.get_player_games_by_month(username, year, month)
    for i in range(len(response4.games)):
        if response4.games[i].pgn and (response4.games[i].pgn[:20] == '[Event "Live Chess"]' or response4.games[i].pgn[:20] == '[Event "Let\'s Play"]'):
            live_games.append(response4.games[i])

In [17]:
def convert_to_timezone(date, timezone):
    date = pd.to_datetime(date)
    date = date.tz_localize('UTC')
    date = str(date.tz_convert(timezone))
    return date[:-9]

In [19]:
def game_info(num):
    if live_games[num].white.username != username:
        opponent = live_games[num].white.username
        my_result = live_games[num].black.result
        opponent_result = live_games[num].white.result
        my_rating = int(live_games[num].black.rating)
        opponent_rating = int(live_games[num].white.rating)
        pieces = 'black'
    else: 
        opponent = live_games[num].black.username
        my_result = live_games[num].white.result
        opponent_result = live_games[num].black.result
        my_rating = int(live_games[num].white.rating)
        opponent_rating = int(live_games[num].black.rating)
        pieces = 'white'
    
    if my_result == 'win':
        result = 'win'
        game_ending = opponent_result
    elif my_result in ['resigned', 'checkmated', 'timeout']:
        result = 'loss'
        game_ending = my_result
    else:
        result = 'draw'
        game_ending = my_result

    list = [pieces, opponent, result, game_ending, my_rating, opponent_rating]
    return list

In [21]:
def time_control(num):
    try:
        time = live_games[num].time_control
        if '+' in time:
            if time[-2] == '+':
                time = str(int(time[:-2])//60) + ' minutes, ' + time[-1] + ' seconds per move'
            else:
                time = str(int(time[:-3])//60) + ' minutes, ' + time[-2:] + ' seconds per move'
        elif live_games[num].time_class == 'daily':
            time = 'daily'
        else:
            time = str(int(time)//60) + ' minutes, ' +  '0 seconds per move'

        if time == '0 minutes, 0 seconds per move':
            time = 'less than 1 minute'
        
        return time
        
    except ValueError:
        time = 'N/A'
        return time

In [233]:
def opening(num):
    url = live_games[num].eco
    pattern1 = r'[^/]+$'
    match1 = re.findall(pattern1, url)
    pattern2 = r'-\d.*$|with-\d.*$|\.{3}.*$'
    match2 = re.sub(pattern2, "", match1[0])
    match3 = re.sub(r'-', " ", match2)
    return match3

In [235]:
# Specify column names
columns = ['Date', 'Played As', 'My Rating', 'Opponent', 'Opponent Rating', 'Result', 'Game Ending', 'Game Type', 'Time Controls', 'Opening', 'URL']

# Create an empty DataFrame
chess_games = pd.DataFrame(columns=columns)

dates = []
played_as = []
my_rating = []
opponent = []
opponent_rating = []
result = []
game_ending = []
game_type = []
controls = []
chess_opening = []
url = []

for i in range(len(live_games)):
    readable_date = datetime.datetime.utcfromtimestamp(live_games[i].end_time)
    dates.append(convert_to_timezone(readable_date, timezone))
    played_as.append(game_info(i)[0])
    opponent.append(game_info(i)[1])
    result.append(game_info(i)[2])
    game_ending.append(game_info(i)[3])
    my_rating.append(game_info(i)[4])
    opponent_rating.append(game_info(i)[5])
    game_type.append(live_games[i].time_class)
    controls.append(time_control(i))
    chess_opening.append(opening(i))
    url.append(live_games[i].url)

chess_games['Date'] = dates
chess_games['Played As'] = played_as
chess_games['My Rating'] = my_rating
chess_games['Opponent'] = opponent
chess_games['Opponent Rating'] = opponent_rating
chess_games['Result'] = result
chess_games['Game Ending'] = game_ending
chess_games['Game Type'] = game_type
chess_games['Time Controls'] = controls
chess_games['Opening'] = chess_opening
chess_games['URL'] = url
chess_games['Year'] = chess_games['Date'].str[:4]
chess_games['Month'] = chess_games['Date'].str[5:7]

In [27]:
def filtered_results(played_as, my_rating_lowerbound, my_rating_upperbound, opponent, opponent_rating_lowerbound, opponent_rating_upperbound, 
                     year, month, result, game_ending, game_type, time_controls, opening):
    global filtered_df
    filtered_df = chess_games
    if played_as != 'ALL':
        filtered_df = filtered_df[filtered_df['Played As'] == played_as]
    if my_rating_lowerbound != 'ALL':
        filtered_df = filtered_df[filtered_df['My Rating'] >= int(my_rating_lowerbound)]
    if my_rating_upperbound != 'ALL':
        filtered_df = filtered_df[filtered_df['My Rating'] <= int(my_rating_upperbound)]
    if opponent != 'ALL':
        filtered_df = filtered_df[filtered_df['Opponent'].str.contains(opponent, case=False, na=False)]
    if opponent_rating_lowerbound != 'ALL':
        filtered_df = filtered_df[filtered_df['Opponent Rating'] >= int(opponent_rating_lowerbound)]
    if opponent_rating_upperbound != 'ALL':
        filtered_df = filtered_df[filtered_df['Opponent Rating'] <= int(opponent_rating_upperbound)]
    if year != 'ALL':
        filtered_df = filtered_df[filtered_df['Year'] == year]
    if month != 'ALL':
        filtered_df = filtered_df[filtered_df['Month'] == month]
    if result != 'ALL':
        filtered_df = filtered_df[filtered_df['Result'] == result]
    if game_ending != 'ALL':
        filtered_df = filtered_df[filtered_df['Game Ending'] == game_ending]
    if game_type != 'ALL':
        filtered_df = filtered_df[filtered_df['Game Type'] == game_type]
    if time_controls != 'ALL':
        filtered_df = filtered_df[filtered_df['Time Controls'] == time_controls]
    if opening != 'ALL':
        filtered_df = filtered_df[filtered_df['Opening'].str.contains(opening, case=False, na=False)]
    filtered_df = filtered_df.reset_index(drop=True)
    return filtered_df.iloc[:, :-2]

In [269]:
## Define your filters.  Specify 'ALL' if you do not want to filter that column. Wildcard search for opponent and opening
played_as = 'ALL'
my_rating_lowerbound = 'ALL'
my_rating_upperbound = 'ALL'
opponent  = 'ALL'
opponent_rating_lowerbound = 'ALL'
opponent_rating_upperbound = 'ALL'
year = 'ALL'
month = 'ALL'
result = 'ALL'
game_ending = 'ALL'
game_type = 'ALL'
time_controls = 'ALL'
opening = 'ALL'

# Calling function to print filtered dataframe
filtered_results(played_as, my_rating_lowerbound, my_rating_upperbound, opponent, opponent_rating_lowerbound, opponent_rating_upperbound,
                 year, month, result, game_ending, game_type, time_controls, opening)

,Date,Played As,My Rating,Opponent,Opponent Rating,Result,Game Ending,Game Type,Time Controls,Opening,URL
0,2014-01-06 18:54,white,2354,Godswill,2167,win,resigned,blitz,"3 minutes, 0 seconds per move",Vienna Game Max Lange Paulsen Variation,https://www.chess.com/game/live/692667823
1,2014-01-06 19:00,black,2438,Godswill,2163,win,timeout,blitz,"3 minutes, 0 seconds per move",Indian Game Accelerated Variation,https://www.chess.com/game/live/692670646
2,2014-01-06 19:35,black,2336,manueliux_06,2104,win,resigned,bullet,"1 minutes, 0 seconds per move",Pirc Defense Modern Defense Geller System,https://www.chess.com/game/live/692695595
3,2014-01-06 19:37,white,2411,manueliux_06,2101,win,resigned,bullet,"1 minutes, 0 seconds per move",Caro Kann Defense Two Knights Attack,https://www.chess.com/game/live/692696567
4,2014-01-06 19:46,white,2509,Dmitriy_From_Russia,2266,win,resigned,blitz,"3 minutes, 0 seconds per move",Kings Indian Defense Fianchetto Variation,https://www.chess.com/game/live/692700868
...,...,...,...,...,...,...,...,...,...,...,...
57598,2024-11-30 12:36,black,3314,KogotBobra17,2734,win,resigned,bullet,"1 minutes, 0 seconds per move",Caro Kann Defense Gurgenidze System,https://www.chess.com/game/live/126727173293
57599,2024-11-30 12:38,white,3318,gurelediz,3111,win,timeout,bullet,"1 minutes, 0 seconds per move",Caro Kann Defense Two Knights Attack,https://www.chess.com/game/live/126727185675
57600,2024-11-30 12:40,black,3319,AlbusSevresPotter,2731,win,resigned,bullet,"1 minutes, 0 seconds per move",Reti Opening Kingside Fianchetto Variation,https://www.chess.com/game/live/126727214495
57601,2024-11-30 12:41,black,3319,Zgorl,2705,win,resigned,bullet,"1 minutes, 0 seconds per move",Queens Pawn Opening,https://www.chess.com/game/live/126727239945
57602,2024-11-30 12:43,white,3322,dropstoneDP,3089,win,resigned,bullet,"1 minutes, 0 seconds per move",Nimzowitsch Larsen Attack Modern Variation,https://www.chess.com/game/live/126727251597

In [219]:
# filtered_df.to_excel('filtered_df.xlsx', index=False)

In [271]:
filtered_df['Result'].value_counts()

Result
win     45490
loss     6958
draw     5155
Name: count, dtype: int64

In [281]:
filtered_df['Opening'].value_counts().head(5)

Opening
Modern Defense                                       2816
Modern Defense Standard Line                         2758
Nimzowitsch Larsen Attack Modern Variation           1903
Reti Opening Nimzowitsch Larsen Attack               1408
Indian Game Knights Variation East Indian Defense    1277
Name: count, dtype: int64

In [275]:
# Group by 'Category' and calculate value counts for 'Subcategory'
grouped = filtered_df.groupby('Opening')['Result'].value_counts().unstack(fill_value=0)

# Calculate win percentage
grouped['win_percentage'] = (grouped['win'] / grouped.sum(axis=1)) * 100
grouped['win_percentage'] = grouped['win_percentage'].round(1)

# Calculate value counts for the 'Category' column
category_counts = filtered_df['Opening'].value_counts()

# Add the value counts as a column in the grouped DataFrame
grouped['count'] = category_counts

# Sort the DataFrame by the value counts
grouped = grouped.loc[category_counts.index]

grouped_reset = grouped.reset_index()
grouped_reset = grouped_reset[['Opening', 'count', 'win_percentage']]
print(grouped_reset.to_string(index=False))

                                                                                     Opening  count  win_percentage
                                                                             Modern Defense    2816            83.0
                                                                Modern Defense Standard Line   2758            81.5
                                                  Nimzowitsch Larsen Attack Modern Variation   1903            79.9
                                                      Reti Opening Nimzowitsch Larsen Attack   1408            80.9
                                           Indian Game Knights Variation East Indian Defense   1277            82.5
                                                   Closed Sicilian Defense Grand Prix Attack    905            87.4
                                                  Reti Opening Kingside Fianchetto Variation    895            86.5
                                                         Reti Opening Nimzo Larsen Variation    820            81.5
                                                                               Owens Defense    785            79.7
                                                        Caro Kann Defense Two Knights Attack    780            84.1
                                               Nimzowitsch Larsen Attack Classical Variation    695            80.7
                                                                              Mieses Opening    674            85.3
                                                            Ruy Lopez Opening Berlin Defense    663            64.4
                                                                         Queens Pawn Opening    582            82.8
                                              Bishops Opening Berlin Vienna Hybrid Variation    578            80.8
                                                                   Nimzowitsch Larsen Attack    508            84.1
                                                            Reti Opening Sicilian Invitation    496            83.3
                                                    Alekhines Defense Scandinavian Variation    485            80.8
                                                         Caro Kann Defense Gurgenidze System    459            83.4
                                                 Scandinavian Defense Mieses Kotrc Main Line    453            70.4
                                               Modern Defense Standard Two Knights Variation    452            81.6
                                                                            Sicilian Defense    451            82.0
                                                                                Reti Opening    431            77.7
                                                      Queens Pawn Opening Chigorin Variation    409            64.5
                                                                           Trompowsky Attack    400            74.8
                                                           English Opening Agincourt Defense    391            78.3
                                                                           Giuoco Piano Game    380            66.6
                                                        Sicilian Defense Chekhover Variation    375            77.6
                                                       English Opening Great Snake Variation    372            86.8
                                                                                 Indian Game    371            75.5
                                                                               London System    358            73.7
                                         Caro Kann Defense Two Knights Mindeno Exchange Line    350            82.6
                                                  Nimzowitsch Larsen Attack Indian Variation    346            88.7
                                              Modern Defense Standard Pseudo Austrian Attack    344            83.1
                                        Reti Opening Kings Indian Attack Symmetrical Defense    343            84.3
                                                                           Caro Kann Defense    333            76.0
                                                        Queens Pawn Opening Krause Variation    333            80.5
                                                                     Closed Sicilian Defense    330            85.2
                                                                     Alapin Sicilian Defense    327            73.7
                                                       Kings Indian Defense Normal Variation    326            82.8
                                                                 Scandinavian Defense Closed    315            78.4
                                                                      Queens Gambit Declined    304            80.3
                                                      Indian Game Spielmann Indian Variation    300            80.7
                                                 French Defense Classical Steinitz Variation    282            84.8
                                                                                Pirc Defense    279            80.6
                                                                              Modern Defense    254            78.3
                                                          French Defense Kings Indian Attack    248            89.5
                                                   Sicilian Defense Delayed Alapin Variation    247            76.9
                                        Ruy Lopez Opening Berlin lHermet Berlin Wall Defense    239            54.8
                                                Ruy Lopez Opening Berlin Rio Gambit Accepted    235            55.7
                                           English Opening Anglo Indian Kings Indian Defense    233            85.0
                                                      Queens Gambit Declined Catalan Opening    228            56.6
                                       Closed Sicilian Defense Grand Prix Schofman Variation    226            86.7
                                                     Modern Defense Averbakh Kotov Variation    226            81.0
                                                      Kings Indian Attack Yugoslav Variation    214            82.7
                                              Modern Defense Pterodactyl Beefeater Variation    213            81.7
                                                           Modern Defense Averbakh Variation    211            81.5
                                                     Bishops Opening Berlin Spielmann Attack    211            80.1
                                     Bishops Opening Berlin Vienna Hybrid Hromadka Variation    200            73.5
                                                                    Kings Fianchetto Opening    196            89.3
                                        Kings Indian Attack Double Fianchetto Pachman System    192            74.0
                                                       English Opening Symmetrical Variation    189            85.2
                                                              Bishops Opening Berlin Defense    186            80.6
                                                Caro Kann Defense Bronstein Larsen Variation    186            74.2
                                                                   Reti Opening Quiet System    186            81.2
                                                                        Van t Kruijs Opening    182            81.3
                                                 Scandinavian Defense Mieses Kotrc Variation    177            71.8
                                                        Caro Kann Defense Exchange Variation    170            74.1
                                                        Kings Indian Attack French Variation    169            89.3
                                             Kings Indian Attack Double Fianchetto Variation    165            70.9
                                                  Ruy Lopez Opening Berlin lHermet Variation    165            30.3
                                                 Slav Defense Modern Quiet Schallopp Defense    163            74.8
                                                       Indian Game Yusupov Rubinstein System    163            84.0
                          Giuoco Piano Game Giuoco Pianissimo Italian Four Knights Variation    156            73.7
                                                               Indian Game Knights Variation    153            74.5
                                                  English Opening Caro Kann Defensive System    148            79.7
                                                  Caro Kann Defense Advance Short Variation     146            74.0
                                                                Reti Opening Dutch Variation    143            78.3
                                                    Closed Sicilian Defense Traditional Line    138            84.8
                                                 Four Knights Game Scotch Variation Accepted    138            68.8
                                                       Indian Game East Indian London System    135            78.5
                                              Scandinavian Defense Modern Marshall Variation    135            84.4
                                                               Vienna Game Max Lange Defense    132            78.8
                                               Queens Pawn Opening Accelerated London System    132            62.9
                                                             Torre Attack Fianchetto Defense    130            81.5
                                                     English Opening Kings English Variation    130            86.2
                                                      Alapin Sicilian Defense Barmen Defense    130            73.8
                                                        Vienna Game Main Line Paulsen Attack    130            76.9
                                                          Caro Kann Defense Breyer Variation    129            82.2
                                                        Queens Indian Defense Spassky System    129            78.3
                                                     Sicilian Defense Open Najdorf Variation    128            80.5
                                                             Ruy Lopez Opening Cozio Defense    126            72.2
                                                        Kings Pawn Opening St George Defense    123            70.7
                                                       Sicilian Defense Kan Knight Variation    120            82.5
                                                     Caro Kann Defense Advance Tal Variation    119            75.6
                                         Vienna Game Frankenstein Dracula Variation Declined    118            78.0
                                                    French Defense Winawer Advance Variation    117            75.2
                                       Kings Indian Defense Orthodox Aronin Taimanov Defense    115            92.2
                                                        Alekhines Defense Exchange Variation    115            83.5
                                                                                   Undefined    114            78.1
                                                               Sicilian Defense Canal Attack    114            70.2
                                              Queens Gambit Declined Three Knights Variation    112            80.4
                                                           French Defense Exchange Variation    109            77.1
                                                Indian Game East Indian Przepiorka Variation    108            70.4
                                                               Birds Opening Dutch Variation    107            86.9
                                     Giuoco Piano Game Main Line Giuoco Pianissimo Variation    106            67.0
                                                   Alekhines Defense Modern Schmid Variation    105            80.0
                                                         Queens Pawn Opening English Defense    104            81.7
                                   Sicilian Defense Open Accelerated Dragon Modern Variation    104            80.8
                                                Closed Sicilian Defense Grand Prix Variation    101            88.1
                                                                   Indian Game London System     99            72.7
                                               Kings Indian Defense Semi Classical Variation     99            83.8
                                                            Pirc Defense Classical Variation     98            83.7
                                                Closed Sicilian Defense Fianchetto Variation     98            88.8
                                                       Slav Defense Modern Quiet Pin Defense     97            80.4
                                                 Nimzowitsch Larsen Attack English Variation     96            78.1
                                       French Defense Knight Variation Two Knights Variation     95            84.2
                                                             French Defense Normal Variation     95            82.1
                                                                        Kings Indian Defense     94            72.3
                                                           Indian Game Accelerated Variation     94            67.0
                                                French Defense Rubinstein Blackburne Defense     93            73.1
                                                         Caro Kann Defense Fantasy Variation     91            79.1
                                                                           Anderssen Opening     91            80.2
                                                                           Four Knights Game     89            64.0
                                                    Dutch Defense Leningrad Warsaw Variation     87            79.3
                                                    Nimzo Indian Defense Classical Variation     87            62.1
                           English Opening Anglo Indian Kings Knight Queens Indian Formation     84            75.0
                                    Ruy Lopez Opening Morphy Defense Modern Steinitz Defense     83            69.9
                            Kings Indian Defense Fianchetto Karlsbad Panno Simagin Variation     83            66.3
                                            Trompowsky Attack Classical Big Center Variation     83            81.9
                                             Sicilian Defense Nyezhmetdinov Rossolimo Attack     83            75.9
                                                            Reti Opening Kings Indian Attack     82            82.9
                                                                         Kings Indian Attack     82            84.1
                                               Sicilian Defense Taimanov Bastrikov Variation     82            90.2
                                             Nimzowitsch Larsen Attack Symmetrical Variation     81            93.8
                                                         Caro Kann Defense Goldman Variation     81            74.1
                          Kings Indian Defense Samisch Bobotsov Korchnoi Petrosian Variation     81            43.2
                                          Sicilian Defense Hyperaccelerated Dragon Variation     81            84.0
                                                                          Old Benoni Defense     80            77.5
                                                           Sicilian Defense French Variation     80            82.5
                                                                               Kadas Opening     79            75.9
                                                          Grunfeld Defense Burille Variation     78            74.4
                                                            Sicilian Defense Canal Main Line     77            71.4
                                                                Modern Defense Geller System     76            84.2
                                                                                Colle System     75            78.7
                                                                 Caro Kann Defense Main Line     74            81.1
                                                     Queens Pawn Opening Zukertort Variation     74            79.7
                                              Mieses Opening Reversed Rat Valencia Variation     74            87.8
                                                  Sicilian Defense Open Najdorf Adams Attack     73            72.6
                                                         Grunfeld Defense Exchange Variation     73            71.2
                                                     Kings Indian Defense Orthodox Variation     72            70.8
                                                         Queens Pawn Opening Horwitz Defense     71            78.9
                                            Kings Indian Defense Orthodox Exchange Variation     71            73.2
                                                         Sicilian Defense Taimanov Variation     70            81.4
                                                        Ruy Lopez Opening Fianchetto Defense     70            74.3
                                                         Vienna Game Max Lange Vienna Gambit     69            97.1
                                             Pirc Defense Main Line Austrian Unzicker Attack     68            82.4
                                          Caro Kann Defense Two Knights Mindeno Retreat Line     68            77.9
                                                 Reti Opening Queenside Fianchetto Variation     68            77.9
                                                          Caro Kann Defense Modern Variation     68            72.1
                                                       Vienna Game Falkbeer Mieses Variation     68            75.0
                                         Reti Opening Reti Gambit Declined Advance Variation     67            71.6
                                              Kings Fianchetto Opening Symmetrical Variation     67            94.0
                                                Nimzo Indian Defense Classical Noa Variation     67            50.7
                                                      Vienna Game Falkbeer Stanley Variation     67            88.1
                                                       Sicilian Defense Kan Modern Variation     66            83.3
                                            Kings Indian Defense Orthodox Positional Defense     66            72.7
                     Sicilian Defense Hyperaccelerated Dragon Fianchetto Pterodactyl Defense     66            74.2
                                                            French Defense St George Defense     66            68.2
                                     French Defense Classical Steinitz Boleslavsky Variation     65            89.2
                                                      Caro Kann Defense Tartakower Variation     64            71.9

In [277]:
filtered_df['Time Controls'].value_counts()

Time Controls
3 minutes, 0 seconds per move      34643
1 minutes, 0 seconds per move      16410
3 minutes, 1 seconds per move       3690
3 minutes, 2 seconds per move        500
1 minutes, 1 seconds per move        410
5 minutes, 0 seconds per move        315
5 minutes, 1 seconds per move        282
10 minutes, 0 seconds per move       264
10 minutes, 2 seconds per move       219
daily                                175
10 minutes, 5 seconds per move       119
5 minutes, 2 seconds per move        107
60 minutes, 45 seconds per move       73
less than 1 minute                    72
15 minutes, 2 seconds per move        64
2 minutes, 0 seconds per move         62
20 minutes, 10 seconds per move       59
15 minutes, 3 seconds per move        48
5 minutes, 5 seconds per move         36
15 minutes, 0 seconds per move        13
25 minutes, 10 seconds per move       11
15 minutes, 10 seconds per move        9
10 minutes, 10 seconds per move        7
2 minutes, 1 seconds per move          6
10 minutes, 3 seconds per move         3
30 minutes, 0 seconds per move         2
5 minutes, 3 seconds per move          1
3 minutes, 5 seconds per move          1
8 minutes, 0 seconds per move          1
20 minutes, 0 seconds per move         1
Name: count, dtype: int64

In [279]:
filtered_df['Game Type'].value_counts()

Game Type
blitz     39654
bullet    16960
rapid       814
daily       175
Name: count, dtype: int64